# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='event',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='social',
            field=models.IntegerField(null=True),
        ),
    ]
