# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20160107_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='decision',
            name='health',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='money',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='social',
        ),
        migrations.AddField(
            model_name='meter',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Decision'),
        ),
    ]
